# Generated by Django 5.2.1 on 2025-09-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=40)),
                ('date', models.DateField()),
            ],
        ),
    ]
