# Generated by Django 5.2.6 on 2025-10-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_person_employee_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=30)),
                ('f2', models.CharField(max_length=30)),
                ('f3', models.CharField(max_length=30)),
                ('f4', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parent2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.parent2')),
                ('f5', models.CharField(max_length=30)),
                ('f6', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('testapp.parent2',),
        ),
    ]
