# Generated by Django 5.2.6 on 2025-10-10 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_parent2_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=30)),
                ('f2', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='parent2',
            name='f1',
        ),
        migrations.RemoveField(
            model_name='parent2',
            name='f2',
        ),
        migrations.RemoveField(
            model_name='parent2',
            name='id',
        ),
        migrations.AlterField(
            model_name='child',
            name='parent2_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.parent2'),
        ),
        migrations.AlterField(
            model_name='parent2',
            name='f3',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='child',
            name='parent1_ptr',
            field=models.OneToOneField(auto_created=True, default=111, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.parent1'),
            preserve_default=False,
        ),
    ]
