# Generated by Django 5.2.6 on 2025-10-10 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_parent1_remove_parent2_f1_remove_parent2_f2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='P1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=30)),
                ('f2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='P2',
            fields=[
                ('f3', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('f4', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent1_ptr',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent2_ptr',
        ),
        migrations.CreateModel(
            name='C1',
            fields=[
                ('p2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.p2')),
                ('p1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.p1')),
                ('f5', models.CharField(max_length=30)),
                ('f6', models.CharField(max_length=30)),
            ],
            bases=('testapp.p1', 'testapp.p2'),
        ),
        migrations.DeleteModel(
            name='Parent1',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Parent2',
        ),
    ]
