from django.shortcuts import render
from django.http import HttpResponse, JsonResponse


# Plain text response
def text_view(request):
    return HttpResponse("This is a Plain Text")

# HTML Response

def html_view(request):
    html = """
        <html>
        <head>
         <title>My Page</title>
         </head>
        
        <body>
            <h1>This is HTML Response Generated by html_view</h1>
            <p>This is random para</p>
            <h2 style='color:red'>HTML text with css</h2>
        </body>

        </html>
        
        """
    
    return HttpResponse(html)



# Json Response 

def json_view(request):
    data = {
        # key : value
        "name":"Mohd Navaid",
        "language":"Python",
        "framework":"Django",
    }

    return JsonResponse(data)