# Generated by Django 5.2.6 on 2025-10-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=40)),
                ('esal', models.FloatField()),
                ('addr', models.CharField(max_length=40)),
            ],
        ),
    ]
