# Generated by Django 5.2.6 on 2025-10-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='addr',
            new_name='eaddr',
        ),
    ]
