# Generated by Django 5.2.1 on 2025-08-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=80)),
                ('date', models.DateField()),
            ],
        ),
    ]
